### ISSUE TITLE
多个provider 如何写的更加优雅

### ISSUE THREAD

**Issue by zystudios** [wuwenbang/hostore#1]
```
 <Store1.Provider>
      <Store2.Provider>
        <Store3.Provider>{children}</Store3.Provider>
      </Store2.Provider>
    </Store1.Provider>
```

比如我N个Provider，除了这种嵌套一层层写，还有啥更优雅的方式？谢谢

我尝试改成一层嵌套，但是没成功
```
<Stoge provider={{[provider1,provider2,provider3]}}>
```

我比较倾向于这种类似的写法

**Comment by leowux** [comment]
@zystudios 感谢您的提议，我在 [feature-compose-providers](https://github.com/leowux/hostore/tree/feature-compose-providers) 分支实现了一版原型，看一下是否符合你的需求：
```tsx
import { ComposeProviders } from "hostore";
const App = () => {
  return (
    // 组合多个 Provider
    <ComposeProviders providers={[CounterStore.Provider, ToggleStore.Provider]}>
      <Child />
    </ComposeProviders>
  );
};
```

**Comment by zystudios** [comment]
> @zystudios 感谢您的提议，我在 [feature-compose-providers](https://github.com/leowux/hostore/tree/feature-compose-providers) 分支实现了一版原型，看一下是否符合你的需求：
> 
> ```tsx
> import { ComposeProviders } from "hostore";
> const App = () => {
>   return (
>     // 组合多个 Provider
>     <ComposeProviders providers={[CounterStore.Provider, ToggleStore.Provider]}>
>       <Child />
>     </ComposeProviders>
>   );
> };
> ```

感谢，看起来好多了，这个轻量版store很实用

**Comment by zystudios** [comment]
谢谢提供这么好用的store，问题解决关闭，

**Comment by leowux** [comment]
@zystudios 感谢对这个 store 的认可和使用，新功能已经发布生产，版本：1.0.0。
使用用例可以参考：https://github.com/leowux/hostore?tab=readme-ov-file#composeproviders-providers-
